
name: Deploy To S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: Create .env file
        run: echo ${{ secrets.ENV }} | base64 --decode > ./.env

      - name: Verify .env file contents
        run: |
          echo "Checking .env variables..."
          source .env
          echo "VITE_BASE_URL is set to $VITE_BASE_URL"
          echo "VITE_KAKAO_KEY is set to [REDACTED]" # 보안을 위해 키는 숨깁니다.
         
      - name: Install npm dependencies
        run: | 
          npm install
          
      - name: Build project
        run: npx vite build

      - name: Upload S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          SOURCE_DIR: 'dist'
          DEST_DIR: 'dist'
          
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: '/*'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
          DISTRIBUTION:  ${{ secrets.CLOUD_FRONT_ID}}
